# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Author')),
                ('preparation_time', models.TimeField(blank=True, null=True, verbose_name='Time required in active preparation')),
                ('idle_time', models.TimeField(blank=True, help_text='e.g. marinating time, standing time', null=True, verbose_name='Waiting time required')),
                ('cook_time', models.TimeField(blank=True, null=True, verbose_name='Time spent actively cooking/baking/grilling')),
                ('outdoor_cooking_friendly', models.BooleanField(default=False, verbose_name='Whether the meal is suitable for outdoor cooking')),
                ('instructions', models.TextField(verbose_name='Instructions')),
            ],
            options={
                'ordering': ('name', 'author'),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Amount used')),
                ('unit_of_measure', models.CharField(blank=True, help_text='pounds, ounces, cups, kilograms, ...', max_length=50, null=True, verbose_name='Unit of measure')),
                ('preparation_method', models.CharField(blank=True, help_text='chopped, diced, julienned, etc.', max_length=50, null=True, verbose_name='Means of preparation')),
                ('ingredient', models.ForeignKey(help_text='Ingredient', on_delete=django.db.models.deletion.CASCADE, to='cookery.Ingredient')),
                ('recipe', models.ForeignKey(help_text='Ingredient', on_delete=django.db.models.deletion.CASCADE, to='cookery.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ingredients', through='cookery.RecipeIngredient', to='cookery.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Tags', to='cookery.RecipeTag'),
        ),
    ]
