# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0002_auto_20160413_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
