# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0004_auto_20160414_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ingredients', related_name='ingredients', through='cookery.RecipeIngredient', to='cookery.Ingredient'),
        ),
    ]
