# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0007_auto_20160415_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'beginner'), (1, 'intermediate'), (2, 'expert'), (3, 'world class'), (None, 'unknown')], null=True, verbose_name='Difficulty'),
        ),
    ]
